name: JSON Lint

on: [push]

jobs:
  jsonlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install jsonlint -g

      - name: Check JSON files
        run: jsonlint -q *.json
